In [99]:
import requests
import pandas as pd
import numpy as np
from geopy.geocoders import Nominatim
from IPython.display import Image 
from IPython.core.display import HTML 
from pandas.io.json import json_normalize
import folium

In [100]:
ClIENT_ID = 'KL3RTTROV0N33KJKSUK0MKY4D12LIQDWUIOHX10M4OBHVH34'
ClIENT_SECRET = 'P45QAU0PNKG4WX1PVNVTGZUP2ZU1ZRNYAMA33HJKSQZJUBF1'
VERSION = '20180604'
LIMIT =30
print('Your credentails:')
print('Foursquare_ID: ' + ClIENT_ID)

print('Foursquare_Secret:' + ClIENT_SECRET)

Your credentails:
Foursquare_ID: KL3RTTROV0N33KJKSUK0MKY4D12LIQDWUIOHX10M4OBHVH34
Foursquare_Secret:P45QAU0PNKG4WX1PVNVTGZUP2ZU1ZRNYAMA33HJKSQZJUBF1

In [101]:
#define city location, latitude, longitude
city = 'Mumbai'
geolocator = Nominatim(user_agent="foursquare_agent")
location = geolocator.geocode(city)
latitude = location.latitude
longitude = location.longitude
print(latitude, longitude)

18.9387711 72.8353355

In [102]:
#searching hotels

In [103]:

# search for hotels
search_query = 'Hotel'
radius = 500

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'\
.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=KL3RTTROV0N33KJKSUK0MKY4D12LIQDWUIOHX10M4OBHVH34&client_secret=P45QAU0PNKG4WX1PVNVTGZUP2ZU1ZRNYAMA33HJKSQZJUBF1&ll=18.9387711,72.8353355&v=20180604&query=Hotel&radius=500&limit=30'

In [104]:

# Sending the GET Request
results = requests.get(url).json()
#if you want to see json file then print results

In [105]:
# assign relevant part of JSON to venues
venues = results['response']['venues']

# tranform venues into a dataframe
dataframe = json_normalize(venues)
dataframe.head()

C:\Users\Acer\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  """

,id,name,categories,referralId,hasPerk,location.address,location.crossStreet,location.lat,location.lng,location.labeledLatLngs,location.distance,location.postalCode,location.cc,location.city,location.state,location.country,location.formattedAddress
0,4e135a03a809291902c7d32f,Hotel Traveller’s Inn,"[{'id': '4bf58dd8d48988d1f8931735', 'name': 'B...",v-1590405162,False,"26, ADI Marzban Path","Behind Cafe Universal, Ballard Estate, Fort",18.936039,72.838000,"[{'label': 'display', 'lat': 18.93603902855253...",413,400001,IN,Mumbai,Mahārāshtra,India,"[26, ADI Marzban Path (Behind Cafe Universal, ..."
1,4bcf4de40ffdce72215fb2c0,Residency Hotel,"[{'id': '4bf58dd8d48988d1fa931735', 'name': 'H...",v-1590405162,False,"26, Corner of D.N. Road and Rustom Sidhwa Marg...",NaN,18.934978,72.833481,"[{'label': 'display', 'lat': 18.93497786680689...",465,400001,IN,Mumbai,Mahārāshtra,India,"[26, Corner of D.N. Road and Rustom Sidhwa Mar..."
2,4cbc460f9552b60c8d81e48b,City Palace Hotel,"[{'id': '4bf58dd8d48988d1fa931735', 'name': 'H...",v-1590405162,False,NaN,NaN,18.938970,72.835610,"[{'label': 'display', 'lat': 18.93897, 'lng': ...",36,NaN,IN,NaN,NaN,India,[India]
3,4ffaf206e4b0a0306dd1271d,Hotel City Palace,[],v-1590405162,False,Near CST,NaN,18.938474,72.834599,"[{'label': 'display', 'lat': 18.93847362379592...",84,NaN,IN,Mumbai,Mahārāshtra,India,"[Near CST, Mumbai, Mahārāshtra, India]"
4,5321eed6498e273e35971c04,sheel hotel,"[{'id': '4bf58dd8d48988d1fa931735', 'name': 'H...",v-1590405162,False,NaN,NaN,18.938211,72.835725,"[{'label': 'display', 'lat': 18.93821144054106...",74,NaN,IN,NaN,NaN,India,[India]

In [106]:
# assign relevant part of JSON to venues
venues = results['response']['venues']

# tranform venues into a dataframe
dataframe = json_normalize(venues)
dataframe.head()

C:\Users\Acer\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  """

,id,name,categories,referralId,hasPerk,location.address,location.crossStreet,location.lat,location.lng,location.labeledLatLngs,location.distance,location.postalCode,location.cc,location.city,location.state,location.country,location.formattedAddress
0,4e135a03a809291902c7d32f,Hotel Traveller’s Inn,"[{'id': '4bf58dd8d48988d1f8931735', 'name': 'B...",v-1590405162,False,"26, ADI Marzban Path","Behind Cafe Universal, Ballard Estate, Fort",18.936039,72.838000,"[{'label': 'display', 'lat': 18.93603902855253...",413,400001,IN,Mumbai,Mahārāshtra,India,"[26, ADI Marzban Path (Behind Cafe Universal, ..."
1,4bcf4de40ffdce72215fb2c0,Residency Hotel,"[{'id': '4bf58dd8d48988d1fa931735', 'name': 'H...",v-1590405162,False,"26, Corner of D.N. Road and Rustom Sidhwa Marg...",NaN,18.934978,72.833481,"[{'label': 'display', 'lat': 18.93497786680689...",465,400001,IN,Mumbai,Mahārāshtra,India,"[26, Corner of D.N. Road and Rustom Sidhwa Mar..."
2,4cbc460f9552b60c8d81e48b,City Palace Hotel,"[{'id': '4bf58dd8d48988d1fa931735', 'name': 'H...",v-1590405162,False,NaN,NaN,18.938970,72.835610,"[{'label': 'display', 'lat': 18.93897, 'lng': ...",36,NaN,IN,NaN,NaN,India,[India]
3,4ffaf206e4b0a0306dd1271d,Hotel City Palace,[],v-1590405162,False,Near CST,NaN,18.938474,72.834599,"[{'label': 'display', 'lat': 18.93847362379592...",84,NaN,IN,Mumbai,Mahārāshtra,India,"[Near CST, Mumbai, Mahārāshtra, India]"
4,5321eed6498e273e35971c04,sheel hotel,"[{'id': '4bf58dd8d48988d1fa931735', 'name': 'H...",v-1590405162,False,NaN,NaN,18.938211,72.835725,"[{'label': 'display', 'lat': 18.93821144054106...",74,NaN,IN,NaN,NaN,India,[India]

In [ ]:
#cleaning

In [107]:
# keep only columns that include venue name, and anything that is associated with location
clean_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')]+ ['id']
clean_dataframe = dataframe.loc[:,clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row
clean_dataframe['categories'] = clean_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_dataframe.columns = [column.split('.')[-1] for column in clean_dataframe.columns]

clean_dataframe.head()

,name,categories,address,crossStreet,lat,lng,labeledLatLngs,distance,postalCode,cc,city,state,country,formattedAddress,id
0,Hotel Traveller’s Inn,Bed & Breakfast,"26, ADI Marzban Path","Behind Cafe Universal, Ballard Estate, Fort",18.936039,72.838000,"[{'label': 'display', 'lat': 18.93603902855253...",413,400001,IN,Mumbai,Mahārāshtra,India,"[26, ADI Marzban Path (Behind Cafe Universal, ...",4e135a03a809291902c7d32f
1,Residency Hotel,Hotel,"26, Corner of D.N. Road and Rustom Sidhwa Marg...",NaN,18.934978,72.833481,"[{'label': 'display', 'lat': 18.93497786680689...",465,400001,IN,Mumbai,Mahārāshtra,India,"[26, Corner of D.N. Road and Rustom Sidhwa Mar...",4bcf4de40ffdce72215fb2c0
2,City Palace Hotel,Hotel,NaN,NaN,18.938970,72.835610,"[{'label': 'display', 'lat': 18.93897, 'lng': ...",36,NaN,IN,NaN,NaN,India,[India],4cbc460f9552b60c8d81e48b
3,Hotel City Palace,None,Near CST,NaN,18.938474,72.834599,"[{'label': 'display', 'lat': 18.93847362379592...",84,NaN,IN,Mumbai,Mahārāshtra,India,"[Near CST, Mumbai, Mahārāshtra, India]",4ffaf206e4b0a0306dd1271d
4,sheel hotel,Hotel,NaN,NaN,18.938211,72.835725,"[{'label': 'display', 'lat': 18.93821144054106...",74,NaN,IN,NaN,NaN,India,[India],5321eed6498e273e35971c04

In [108]:
# delete unnecessary columns
clean_dataframe2= clean_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress','labeledLatLngs', 'id'], axis=1)
clean_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Hotel Traveller’s Inn,Bed & Breakfast,"26, ADI Marzban Path",18.936039,72.838000,400001,Mahārāshtra
1,Residency Hotel,Hotel,"26, Corner of D.N. Road and Rustom Sidhwa Marg...",18.934978,72.833481,400001,Mahārāshtra
2,City Palace Hotel,Hotel,NaN,18.938970,72.835610,NaN,NaN
3,Hotel City Palace,None,Near CST,18.938474,72.834599,NaN,Mahārāshtra
4,sheel hotel,Hotel,NaN,18.938211,72.835725,NaN,NaN
5,Hotel Fountain Plaza,Indian Restaurant,"panthaky house, Raghunath dadaji street",18.935671,72.834030,NaN,Mahārāshtra
6,hotel kalapi,Motel,NaN,18.938184,72.837802,NaN,NaN
7,Hotel Landmark Fort,Bed & Breakfast,249 P D Mello Road,18.938528,72.837998,400001,Mahārāshtra
8,Colaba Grand Hotel,Hotel Bar,Colaba,18.939656,72.836457,NaN,Mahārāshtra
9,Hotel Landmark Annexe,Hotel,NaN,18.938030,72.838844,400001,Mahārāshtra
10,Hotel Windsor,Hostel,Kumptha 10,18.936808,72.838327,NaN,Mahārāshtra
11,Hotel Ankitakshita,Hotel,NaN,18.935698,72.837123,400023,Mahārāshtra
12,Hotel Arkshita,Snack Place,NaN,18.935647,72.837311,NaN,NaN
13,Hotel Anand Bhuvan,Fast Food Restaurant,Opposite Shahid bhagat Singh Road,18.935345,72.836884,400001,Mahārāshtra
14,Hotel Ashoka,Indian Restaurant,NaN,18.942741,72.834501,NaN,NaN
15,Hotel Outram,Hotel,NaN,18.936418,72.831732,NaN,NaN
16,Hotel Dolphin,Hotel,"327,SBS Road",18.934567,72.836942,NaN,Mahārāshtra
17,Welcome Hotel,Motel,257 Shahid Bhagat Singh Rd.,18.937703,72.837467,NaN,Mahārāshtra
18,landmark hotel mumbai,Residential Building (Apartment / Condo),NaN,18.938465,72.838217,NaN,NaN
19,hotel golden palm fort,Hotel Pool,Fort,18.933103,72.834628,NaN,Mahārāshtra
20,Deluxe Hotel,Housing Development,287 Shahid Bhagat Singh Road,18.935690,72.837398,400001,Mahārāshtra
21,Benazeer Hotel,Hotel,16 Gunbow Street,18.935140,72.833948,400001,Mahārāshtra
22,A.k. International Hotel,Hotel,NaN,18.935867,72.837875,NaN,NaN
23,Cenora Hotel,Asian Restaurant,NaN,18.934916,72.836969,NaN,NaN
24,Whatson's Hotel,Hotel,Fort,18.934662,72.836778,NaN,Mahārāshtra
25,"Mumbai Hotels, India",Hotel,Mumbai,18.939616,72.835665,NaN,Mahārāshtra
26,New Anand Bhavan,Fast Food Restaurant,Sheri House,18.934656,72.834848,400023,Mahārāshtra

In [109]:

# delete rows with none values
clean_dataframe3 = clean_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
clean_dataframe3

,name,categories,address,lat,lng,postalCode,state
0,Hotel Traveller’s Inn,Bed & Breakfast,"26, ADI Marzban Path",18.936039,72.838000,400001,Mahārāshtra
1,Residency Hotel,Hotel,"26, Corner of D.N. Road and Rustom Sidhwa Marg...",18.934978,72.833481,400001,Mahārāshtra
7,Hotel Landmark Fort,Bed & Breakfast,249 P D Mello Road,18.938528,72.837998,400001,Mahārāshtra
13,Hotel Anand Bhuvan,Fast Food Restaurant,Opposite Shahid bhagat Singh Road,18.935345,72.836884,400001,Mahārāshtra
20,Deluxe Hotel,Housing Development,287 Shahid Bhagat Singh Road,18.935690,72.837398,400001,Mahārāshtra
21,Benazeer Hotel,Hotel,16 Gunbow Street,18.935140,72.833948,400001,Mahārāshtra
26,New Anand Bhavan,Fast Food Restaurant,Sheri House,18.934656,72.834848,400023,Mahārāshtra

In [110]:
# delete rows which its category is not Hotel or Event Space
array= ['Hotel', 'Event Space']
hotel_dataframe= clean_dataframe3.loc[clean_dataframe3['categories'].isin(array)]
hotel_dataframe

,name,categories,address,lat,lng,postalCode,state
1,Residency Hotel,Hotel,"26, Corner of D.N. Road and Rustom Sidhwa Marg...",18.934978,72.833481,400001,Mahārāshtra
21,Benazeer Hotel,Hotel,16 Gunbow Street,18.935140,72.833948,400001,Mahārāshtra

In [111]:
# delete rows which has duplicate hotel's name
df_hotels = hotel_dataframe.drop_duplicates(subset='name', keep="first")
df_hotels

,name,categories,address,lat,lng,postalCode,state
1,Residency Hotel,Hotel,"26, Corner of D.N. Road and Rustom Sidhwa Marg...",18.934978,72.833481,400001,Mahārāshtra
21,Benazeer Hotel,Hotel,16 Gunbow Street,18.935140,72.833948,400001,Mahārāshtra

In [112]:
# choose the hotel which has the same postalCode with the event space
df_hotel = df_hotels[df_hotels.postalCode == '400001']
df_hotel

,name,categories,address,lat,lng,postalCode,state
1,Residency Hotel,Hotel,"26, Corner of D.N. Road and Rustom Sidhwa Marg...",18.934978,72.833481,400001,Mahārāshtra
21,Benazeer Hotel,Hotel,16 Gunbow Street,18.935140,72.833948,400001,Mahārāshtra

In [ ]:
#parks

In [113]:
# search for Parks
search_query = 'Park'
radius = 10000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'\
.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=KL3RTTROV0N33KJKSUK0MKY4D12LIQDWUIOHX10M4OBHVH34&client_secret=P45QAU0PNKG4WX1PVNVTGZUP2ZU1ZRNYAMA33HJKSQZJUBF1&ll=18.9387711,72.8353355&v=20180604&query=Park&radius=10000&limit=30'

In [114]:
# Send the GET Request and examine the results
presults = requests.get(url).json()
#presults

In [115]:
 #assign relevant part of JSON to venues
venues = presults['response']['venues']

# tranform venues into a dataframe
park_dataframe = json_normalize(venues)
park_dataframe.head()

C:\Users\Acer\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  """

,id,name,categories,referralId,hasPerk,location.address,location.crossStreet,location.lat,location.lng,location.labeledLatLngs,location.distance,location.postalCode,location.cc,location.city,location.state,location.country,location.formattedAddress,venuePage.id
0,511e3da9e4b092d8057a44b6,Harish Mahindra Children's Park,"[{'id': '4bf58dd8d48988d163941735', 'name': 'P...",v-1590405164,False,"Breach Candy, Behind American Counsulate",Bhulabhai Desai Road,18.914867,72.823688,"[{'label': 'display', 'lat': 18.91486679408915...",2930,400026,IN,Mumbai,Mahārāshtra,India,"[Breach Candy, Behind American Counsulate (Bhu...",NaN
1,52f2771d11d2afc107a8206d,Traditions at Reagan Park,"[{'id': '5267e4d9e4b0ec79466e48c6', 'name': 'C...",v-1590405164,False,1176 Kingwood Drive,NaN,18.949804,72.834699,"[{'label': 'display', 'lat': 18.94980408771263...",1230,46123,IN,Avon,Indiana,India,"[1176 Kingwood Drive, Avon 46123, Indiana, India]",NaN
2,4c84af7ed34ca14342c74080,Park Avenue,"[{'id': '4bf58dd8d48988d103951735', 'name': 'C...",v-1590405164,False,"in High Street Phoenix,",NaN,18.996986,72.826677,"[{'label': 'display', 'lat': 18.99698589447507...",6544,NaN,IN,Mumbai,Mahārāshtra,India,"[in High Street Phoenix,, Mumbai, Mahārāshtra,...",NaN
3,5b430c7f2b274a002c36a513,Rivali Park,"[{'id': '5032885091d4c4b30a586d66', 'name': 'R...",v-1590405164,False,"Rivali Park, Western Express Highway,Borivali ...",NaN,18.929599,72.828181,"[{'label': 'display', 'lat': 18.92959945134227...",1268,400066,IN,NaN,Mahārāshtra,India,"[Rivali Park, Western Express Highway,Borivali...",NaN
4,4c9174ec238c6dcb067ec055,Priyadarshini Park,"[{'id': '4bf58dd8d48988d163941735', 'name': 'P...",v-1590405164,False,Nepean Sea Road,NaN,18.957515,72.799614,"[{'label': 'display', 'lat': 18.95751519120163...",4301,400006,IN,Mumbai,Mahārāshtra,India,"[Nepean Sea Road, Mumbai 400006, Mahārāshtra, ...",NaN

In [116]:
# keep only columns that include venue name, and anything that is associated with location
park_clean_columns = ['name', 'categories'] + [col for col in park_dataframe.columns if col.startswith('location.')]+ ['id']
clean_park_dataframe = park_dataframe.loc[:,park_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list1 = row['categories']
    except:
        categories_list1 = row['venue.categories']
        
    if len(categories_list1) == 0:
        return None
    else:
        return categories_list1[0]['name']

# filter the category for each row
clean_park_dataframe['categories'] = clean_park_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_park_dataframe.columns = [column.split('.')[-1] for column in clean_park_dataframe.columns]

clean_park_dataframe.head()

,name,categories,address,crossStreet,lat,lng,labeledLatLngs,distance,postalCode,cc,city,state,country,formattedAddress,id
0,Harish Mahindra Children's Park,Park,"Breach Candy, Behind American Counsulate",Bhulabhai Desai Road,18.914867,72.823688,"[{'label': 'display', 'lat': 18.91486679408915...",2930,400026,IN,Mumbai,Mahārāshtra,India,"[Breach Candy, Behind American Counsulate (Bhu...",511e3da9e4b092d8057a44b6
1,Traditions at Reagan Park,Conference,1176 Kingwood Drive,NaN,18.949804,72.834699,"[{'label': 'display', 'lat': 18.94980408771263...",1230,46123,IN,Avon,Indiana,India,"[1176 Kingwood Drive, Avon 46123, Indiana, India]",52f2771d11d2afc107a8206d
2,Park Avenue,Clothing Store,"in High Street Phoenix,",NaN,18.996986,72.826677,"[{'label': 'display', 'lat': 18.99698589447507...",6544,NaN,IN,Mumbai,Mahārāshtra,India,"[in High Street Phoenix,, Mumbai, Mahārāshtra,...",4c84af7ed34ca14342c74080
3,Rivali Park,Real Estate Office,"Rivali Park, Western Express Highway,Borivali ...",NaN,18.929599,72.828181,"[{'label': 'display', 'lat': 18.92959945134227...",1268,400066,IN,NaN,Mahārāshtra,India,"[Rivali Park, Western Express Highway,Borivali...",5b430c7f2b274a002c36a513
4,Priyadarshini Park,Park,Nepean Sea Road,NaN,18.957515,72.799614,"[{'label': 'display', 'lat': 18.95751519120163...",4301,400006,IN,Mumbai,Mahārāshtra,India,"[Nepean Sea Road, Mumbai 400006, Mahārāshtra, ...",4c9174ec238c6dcb067ec055

In [117]:
# delete unnecessary columns
clean_park_dataframe2= clean_park_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'id'], axis=1)
clean_park_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Harish Mahindra Children's Park,Park,"Breach Candy, Behind American Counsulate",18.914867,72.823688,400026,Mahārāshtra
1,Traditions at Reagan Park,Conference,1176 Kingwood Drive,18.949804,72.834699,46123,Indiana
2,Park Avenue,Clothing Store,"in High Street Phoenix,",18.996986,72.826677,NaN,Mahārāshtra
3,Rivali Park,Real Estate Office,"Rivali Park, Western Express Highway,Borivali ...",18.929599,72.828181,400066,Mahārāshtra
4,Priyadarshini Park,Park,Nepean Sea Road,18.957515,72.799614,400006,Mahārāshtra
5,Park Avenue,Men's Store,"Shop No. 32/34, Churchgate House, Veer Nariman...",18.920214,72.830151,400001,Mahārāshtra
6,Peninsula Corporate Park,Building,Lower Parel,18.998626,72.825408,400013,Mahārāshtra
7,Hotel Residency Park,Hotel,NaN,18.953120,72.835175,400003,Mahārāshtra
8,Hotel Residency Park,Hotel,NaN,18.953255,72.835320,NaN,NaN
9,One Avighna Park,Housing Development,"Mahadev Palav Marg, Parel",18.994041,72.834806,400012,Mahārāshtra
10,Badhwar Park,Neighborhood,NaN,18.921100,72.827300,NaN,NaN
11,Kanha National Park,Other Great Outdoors,NaN,18.923037,72.822986,NaN,Madhya Pradesh
12,Park Shilton,Restaurant,NaN,18.965763,72.819282,NaN,NaN
13,China Garden Shivaji Park ¤,Chinese Restaurant,"Cadell Road, Opposite Catering College",19.023244,72.835148,NaN,Mahārāshtra
14,Traffic Park,Park,"Cooperage Rd, Colaba, Mumbai, Maharashtra",18.918844,72.825933,NaN,Mahārāshtra
15,Badhwar Park,Housing Development,Wodehouse Road,18.919160,72.826648,NaN,Mahārāshtra
16,Park View,Residential Building (Apartment / Condo),NaN,18.973326,72.823997,NaN,NaN
17,Badhwar Park,Residential Building (Apartment / Condo),Colaba,18.918839,72.828051,400005,Mahārāshtra
18,saifee park,Residential Building (Apartment / Condo),NaN,18.972489,72.839654,NaN,NaN
19,Bhakti Park,Housing Development,Near Imax Adlabs,19.027670,72.880010,400037,Mahārāshtra
20,Bhakti Park Monorail Station,Light Rail Station,Bhakti Park,19.029101,72.877627,NaN,Mahārāshtra
21,Priyadarshini Park Gym,Gym / Fitness Center,NaN,18.956859,72.799193,NaN,NaN
22,Land's End Park,Park,NaN,18.916561,72.816366,NaN,NaN
23,"Amarsons Park, Breach Candy",Park,NaN,18.972317,72.806327,NaN,NaN
24,Park Avenue Women,Women's Store,NaN,18.995185,72.824560,NaN,NaN
25,Shivaji Park,Playground,Swatantrya Veer Savarkar Marg,19.026621,72.841033,400 028,Mahārāshtra
26,Park Avenue,Clothing Store,"Sky Zone, phoenix mills",18.995051,72.823619,NaN,Mahārāshtra
27,Hill Park,Residential Building (Apartment / Condo),Malabar Hill,18.951897,72.799129,400006,Mahārāshtra
28,Rizvi Park,Residential Building (Apartment / Condo),NaN,18.967114,72.812373,NaN,NaN
29,Green park,None,NaN,18.947203,72.795165,NaN,Mahārāshtra

In [118]:

# delete rows with none values
clean_park_dataframe3 = clean_park_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
clean_park_dataframe3

,name,categories,address,lat,lng,postalCode,state
0,Harish Mahindra Children's Park,Park,"Breach Candy, Behind American Counsulate",18.914867,72.823688,400026,Mahārāshtra
1,Traditions at Reagan Park,Conference,1176 Kingwood Drive,18.949804,72.834699,46123,Indiana
3,Rivali Park,Real Estate Office,"Rivali Park, Western Express Highway,Borivali ...",18.929599,72.828181,400066,Mahārāshtra
4,Priyadarshini Park,Park,Nepean Sea Road,18.957515,72.799614,400006,Mahārāshtra
5,Park Avenue,Men's Store,"Shop No. 32/34, Churchgate House, Veer Nariman...",18.920214,72.830151,400001,Mahārāshtra
6,Peninsula Corporate Park,Building,Lower Parel,18.998626,72.825408,400013,Mahārāshtra
9,One Avighna Park,Housing Development,"Mahadev Palav Marg, Parel",18.994041,72.834806,400012,Mahārāshtra
17,Badhwar Park,Residential Building (Apartment / Condo),Colaba,18.918839,72.828051,400005,Mahārāshtra
19,Bhakti Park,Housing Development,Near Imax Adlabs,19.027670,72.880010,400037,Mahārāshtra
25,Shivaji Park,Playground,Swatantrya Veer Savarkar Marg,19.026621,72.841033,400 028,Mahārāshtra
27,Hill Park,Residential Building (Apartment / Condo),Malabar Hill,18.951897,72.799129,400006,Mahārāshtra

In [119]:

# delete rows which its category is not Park
df_park = clean_park_dataframe3[clean_park_dataframe3.categories == 'Park']
df_park

,name,categories,address,lat,lng,postalCode,state
0,Harish Mahindra Children's Park,Park,"Breach Candy, Behind American Counsulate",18.914867,72.823688,400026,Mahārāshtra
4,Priyadarshini Park,Park,Nepean Sea Road,18.957515,72.799614,400006,Mahārāshtra

In [ ]:
#Restaurants

In [120]:
# search for Restaurants
search_query = 'Restaurant'
radius = 10000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=KL3RTTROV0N33KJKSUK0MKY4D12LIQDWUIOHX10M4OBHVH34&client_secret=P45QAU0PNKG4WX1PVNVTGZUP2ZU1ZRNYAMA33HJKSQZJUBF1&ll=18.9387711,72.8353355&v=20180604&query=Restaurant&radius=10000&limit=30'

In [121]:
# Send the GET Request and examine the results
Rresults = requests.get(url).json()
#Rresults

In [122]:

# assign relevant part of JSON to venues
venues = Rresults['response']['venues']

# tranform venues into a dataframe
Restaurant_dataframe = json_normalize(venues)
Restaurant_dataframe.head()

C:\Users\Acer\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  """

,id,name,categories,referralId,hasPerk,location.address,location.crossStreet,location.lat,location.lng,location.labeledLatLngs,location.distance,location.postalCode,location.cc,location.city,location.state,location.country,location.formattedAddress
0,5263f0f5498edc1ad5f3270f,Nanumal Bhojraj Restaurant - Fort,"[{'id': '4bf58dd8d48988d10f941735', 'name': 'I...",v-1590405165,False,"Near GPO, Fort, VT",S. Bhagat Singh Road,18.937974,72.837663,"[{'label': 'display', 'lat': 18.93797448587734...",260,400001,IN,Mumbai,Mahārāshtra,India,"[Near GPO, Fort, VT (S. Bhagat Singh Road), Mu..."
1,4e4c0a4122713bd908c641ff,Farhang Restaurant,"[{'id': '4bf58dd8d48988d1cc941735', 'name': 'S...",v-1590405165,False,Opposite GPO,Ballard Estate,18.938165,72.837917,"[{'label': 'display', 'lat': 18.93816453050136...",280,NaN,IN,Mumbai,Mahārāshtra,India,"[Opposite GPO (Ballard Estate), Mumbai, Mahārā..."
2,4fb5276be4b0b34b9ac27a1b,Iran Like Restaurant,"[{'id': '4bf58dd8d48988d10f941735', 'name': 'I...",v-1590405165,False,"Palton Road, Near Haj House",NaN,18.945343,72.836809,"[{'label': 'display', 'lat': 18.94534293649397...",747,400001,IN,Mumbai,Mahārāshtra,India,"[Palton Road, Near Haj House, Mumbai 400001, M..."
3,4d9f2bfe9b91a1cda6c365c0,New Majestic Restaurant,"[{'id': '4bf58dd8d48988d10f941735', 'name': 'I...",v-1590405165,False,Opp CST,NaN,18.938972,72.835517,"[{'label': 'display', 'lat': 18.93897156089674...",29,NaN,IN,Mumbai,Mahārāshtra,India,"[Opp CST, Mumbai, Mahārāshtra, India]"
4,4f489f23e4b018635344413a,Panchratna restaurant & bar,"[{'id': '4bf58dd8d48988d10f941735', 'name': 'I...",v-1590405165,False,Opp. Metro Cinema,Marine Lines,18.942900,72.826820,"[{'label': 'display', 'lat': 18.94289961203775...",1007,NaN,IN,Mumbai,Mahārāshtra,India,"[Opp. Metro Cinema (Marine Lines), Mumbai, Mah..."

In [123]:

# keep only columns that include venue name, and anything that is associated with location
Restaurant_clean_columns = ['name', 'categories'] + [col for col in Restaurant_dataframe.columns if col.startswith('location.')]+ ['id']
clean_Restaurant_dataframe = Restaurant_dataframe.loc[:,Restaurant_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list3 = row['categories']
    except:
        categories_list3 = row['venue.categories']
        
    if len(categories_list3) == 0:
        return None
    else:
        return categories_list3[0]['name']

# filter the category for each row
clean_Restaurant_dataframe['categories'] = clean_Restaurant_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_Restaurant_dataframe.columns = [column.split('.')[-1] for column in clean_Restaurant_dataframe.columns]

clean_Restaurant_dataframe.head()

,name,categories,address,crossStreet,lat,lng,labeledLatLngs,distance,postalCode,cc,city,state,country,formattedAddress,id
0,Nanumal Bhojraj Restaurant - Fort,Indian Restaurant,"Near GPO, Fort, VT",S. Bhagat Singh Road,18.937974,72.837663,"[{'label': 'display', 'lat': 18.93797448587734...",260,400001,IN,Mumbai,Mahārāshtra,India,"[Near GPO, Fort, VT (S. Bhagat Singh Road), Mu...",5263f0f5498edc1ad5f3270f
1,Farhang Restaurant,Steakhouse,Opposite GPO,Ballard Estate,18.938165,72.837917,"[{'label': 'display', 'lat': 18.93816453050136...",280,NaN,IN,Mumbai,Mahārāshtra,India,"[Opposite GPO (Ballard Estate), Mumbai, Mahārā...",4e4c0a4122713bd908c641ff
2,Iran Like Restaurant,Indian Restaurant,"Palton Road, Near Haj House",NaN,18.945343,72.836809,"[{'label': 'display', 'lat': 18.94534293649397...",747,400001,IN,Mumbai,Mahārāshtra,India,"[Palton Road, Near Haj House, Mumbai 400001, M...",4fb5276be4b0b34b9ac27a1b
3,New Majestic Restaurant,Indian Restaurant,Opp CST,NaN,18.938972,72.835517,"[{'label': 'display', 'lat': 18.93897156089674...",29,NaN,IN,Mumbai,Mahārāshtra,India,"[Opp CST, Mumbai, Mahārāshtra, India]",4d9f2bfe9b91a1cda6c365c0
4,Panchratna restaurant & bar,Indian Restaurant,Opp. Metro Cinema,Marine Lines,18.942900,72.826820,"[{'label': 'display', 'lat': 18.94289961203775...",1007,NaN,IN,Mumbai,Mahārāshtra,India,"[Opp. Metro Cinema (Marine Lines), Mumbai, Mah...",4f489f23e4b018635344413a

In [124]:
# delete unnecessary columns
clean_Restaurant_dataframe2= clean_Restaurant_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'id'], axis=1)
clean_Restaurant_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Nanumal Bhojraj Restaurant - Fort,Indian Restaurant,"Near GPO, Fort, VT",18.937974,72.837663,400001,Mahārāshtra
1,Farhang Restaurant,Steakhouse,Opposite GPO,18.938165,72.837917,NaN,Mahārāshtra
2,Iran Like Restaurant,Indian Restaurant,"Palton Road, Near Haj House",18.945343,72.836809,400001,Mahārāshtra
3,New Majestic Restaurant,Indian Restaurant,Opp CST,18.938972,72.835517,NaN,Mahārāshtra
4,Panchratna restaurant & bar,Indian Restaurant,Opp. Metro Cinema,18.942900,72.826820,NaN,Mahārāshtra
5,Stadium Restaurant & Stores,Indian Restaurant,Veer Nariman Road,18.933173,72.826929,400023,Mahārāshtra
6,Sai Pooja Restaurant,None,NaN,18.938357,72.835073,NaN,Mahārāshtra
7,Poonam Restaurant,Restaurant,NaN,18.939225,72.835707,NaN,NaN
8,Aram Restaurant,Asian Restaurant,"Capitol building, DN Road",18.939543,72.834495,NaN,Mahārāshtra
9,Nanumal Bhojraj Restaurant - Masjid Bunder,Indian Restaurant,"Gaumukh Bhawan, Masjid Bunder West, Near Masji...",18.953200,72.837577,400009,Mahārāshtra
10,Kalpana restaurant,None,Gpo,18.937489,72.836157,NaN,Mahārāshtra
11,Kamat's Restaurant,Indian Restaurant,"Opp. Electric House, Colaba",18.921570,72.831004,NaN,Mahārāshtra
12,Gulshan Restaurant,Indian Restaurant,NaN,18.938199,72.837764,400001,Mahārāshtra
13,Sind Punjab Bar & Restaurant,Restaurant,"263, SBS Road, Fort, Mumbai",18.937048,72.837381,NaN,NaN
14,Mangalore naaz Restaurant,Asian Restaurant,NaN,18.937245,72.837606,NaN,NaN
15,Bombay Restaurant,Indian Restaurant,NaN,18.935902,72.834426,NaN,Mahārāshtra
16,Canara Restaurant,Indian Restaurant,NaN,18.936847,72.837525,NaN,NaN
17,Anubhav Restaurant & Bar,Indian Restaurant,NaN,18.936497,72.837586,400001,Mahārāshtra
18,Lalit restaurant,Bar,Cawasji Patel road,18.935002,72.833791,400001,Mahārāshtra
19,Kayani Restaurant,Irani Cafe,NaN,18.935040,72.836941,NaN,NaN
20,Goodluck Restaurant,None,NaN,18.935578,72.837357,NaN,Mahārāshtra
21,Pine Restaurant,Indian Restaurant,"Nawab Tank Bunder, Dockyard",18.964799,72.844015,400010,Mahārāshtra
22,Excellensea Restaurant,BBQ Joint,Mint Road,18.935266,72.837240,400001,Mahārāshtra
23,Royal China Restaurant,Cantonese Restaurant,NaN,18.937876,72.831005,NaN,NaN
24,National Restaurant,Food,opp fort market,18.935112,72.836896,400001,Mahārāshtra
25,Brighton Restaurant,Restaurant,NaN,18.935007,72.833687,NaN,NaN
26,Golden Wheel Restaurant,Restaurant,Girgaon,18.954636,72.819690,NaN,Mahārāshtra
27,Fountain Sizzlers Restaurant,Steakhouse,57 Mahatma Gandhi Road,18.931366,72.831462,400 023,Mahārāshtra
28,Welcome Restaurant,Indian Restaurant,NaN,18.942531,72.831328,NaN,NaN
29,Fort restaurant,None,Fort,18.933971,72.833605,NaN,Mahārāshtra

In [125]:
# delete rows with none values
df_Restaurant = clean_Restaurant_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
df_Restaurant

,name,categories,address,lat,lng,postalCode,state
0,Nanumal Bhojraj Restaurant - Fort,Indian Restaurant,"Near GPO, Fort, VT",18.937974,72.837663,400001,Mahārāshtra
2,Iran Like Restaurant,Indian Restaurant,"Palton Road, Near Haj House",18.945343,72.836809,400001,Mahārāshtra
5,Stadium Restaurant & Stores,Indian Restaurant,Veer Nariman Road,18.933173,72.826929,400023,Mahārāshtra
9,Nanumal Bhojraj Restaurant - Masjid Bunder,Indian Restaurant,"Gaumukh Bhawan, Masjid Bunder West, Near Masji...",18.953200,72.837577,400009,Mahārāshtra
18,Lalit restaurant,Bar,Cawasji Patel road,18.935002,72.833791,400001,Mahārāshtra
21,Pine Restaurant,Indian Restaurant,"Nawab Tank Bunder, Dockyard",18.964799,72.844015,400010,Mahārāshtra
22,Excellensea Restaurant,BBQ Joint,Mint Road,18.935266,72.837240,400001,Mahārāshtra
24,National Restaurant,Food,opp fort market,18.935112,72.836896,400001,Mahārāshtra
27,Fountain Sizzlers Restaurant,Steakhouse,57 Mahatma Gandhi Road,18.931366,72.831462,400 023,Mahārāshtra

In [ ]:
#Cafeteria

In [126]:
# search for Cafeteria
search_query = 'Cafeteria'
radius = 10000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=KL3RTTROV0N33KJKSUK0MKY4D12LIQDWUIOHX10M4OBHVH34&client_secret=P45QAU0PNKG4WX1PVNVTGZUP2ZU1ZRNYAMA33HJKSQZJUBF1&ll=18.9387711,72.8353355&v=20180604&query=Cafeteria&radius=10000&limit=30'

In [127]:
# Send the GET Request and examine the results
cresults = requests.get(url).json()
#cresults

In [128]:

# assign relevant part of JSON to venues
venues = cresults['response']['venues']

# tranform venues into a dataframe
Cafeteria_dataframe = json_normalize(venues)
Cafeteria_dataframe.head()

C:\Users\Acer\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  """

,id,name,categories,referralId,hasPerk,location.address,location.lat,location.lng,location.labeledLatLngs,location.distance,location.postalCode,location.cc,location.city,location.state,location.country,location.formattedAddress,location.crossStreet
0,4e81776030f86985e40abb54,Cafeteria,"[{'id': '4bf58dd8d48988d16d941735', 'name': 'C...",v-1590405168,False,Breach Candy Hospital,18.971833,72.804981,"[{'label': 'display', 'lat': 18.97183316652913...",4874,400026,IN,Mumbai,Mahārāshtra,India,"[Breach Candy Hospital, Mumbai 400026, Mahārās...",NaN
1,50050da9e4b0d73a8dfa7ee9,Cafeteria at Tata Capital,"[{'id': '4bf58dd8d48988d120951735', 'name': 'F...",v-1590405168,False,One Forbes,18.930769,72.835434,"[{'label': 'display', 'lat': 18.930769, 'lng':...",890,NaN,IN,Mumbai,Mahārāshtra,India,"[One Forbes (Kala Ghoda), Mumbai, Mahārāshtra,...",Kala Ghoda
2,4e2943f02271752a459cb122,Mumbai High Court Cafeteria,"[{'id': '4bf58dd8d48988d120951735', 'name': 'F...",v-1590405168,False,Fort,18.933198,72.829170,"[{'label': 'display', 'lat': 18.93319755884302...",898,NaN,IN,Mumbai,Mahārāshtra,India,"[Fort, Mumbai, Mahārāshtra, India]",NaN
3,4bdfcc5affdec9286e31eda1,Cafeteria at Indian Hotels,[],v-1590405168,False,Oxford Towers,18.922937,72.832849,"[{'label': 'display', 'lat': 18.922937, 'lng':...",1781,NaN,IN,NaN,Mahārāshtra,India,"[Oxford Towers, Mahārāshtra, India]",NaN
4,4d53497cd4a6721ec05589ac,Cafeteria,[],v-1590405168,False,Mumbai central station,18.970839,72.820636,"[{'label': 'display', 'lat': 18.97083858982881...",3890,NaN,IN,Mumbai,Mahārāshtra,India,"[Mumbai central station, Mumbai, Mahārāshtra, ...",NaN

In [129]:
# keep only columns that include venue name, and anything that is associated with location
Cafeteria_clean_columns = ['name', 'categories'] + [col for col in Cafeteria_dataframe.columns if col.startswith('location.')]+ ['id']
clean_Cafeteria_dataframe = Cafeteria_dataframe.loc[:,Cafeteria_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list4 = row['categories']
    except:
        categories_list4 = row['venue.categories']
        
    if len(categories_list4) == 0:
        return None
    else:
        return categories_list4[0]['name']

# filter the category for each row
clean_Cafeteria_dataframe['categories'] = clean_Cafeteria_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_Cafeteria_dataframe.columns = [column.split('.')[-1] for column in clean_Cafeteria_dataframe.columns]

clean_Cafeteria_dataframe.head()

,name,categories,address,lat,lng,labeledLatLngs,distance,postalCode,cc,city,state,country,formattedAddress,crossStreet,id
0,Cafeteria,Café,Breach Candy Hospital,18.971833,72.804981,"[{'label': 'display', 'lat': 18.97183316652913...",4874,400026,IN,Mumbai,Mahārāshtra,India,"[Breach Candy Hospital, Mumbai 400026, Mahārās...",NaN,4e81776030f86985e40abb54
1,Cafeteria at Tata Capital,Food Court,One Forbes,18.930769,72.835434,"[{'label': 'display', 'lat': 18.930769, 'lng':...",890,NaN,IN,Mumbai,Mahārāshtra,India,"[One Forbes (Kala Ghoda), Mumbai, Mahārāshtra,...",Kala Ghoda,50050da9e4b0d73a8dfa7ee9
2,Mumbai High Court Cafeteria,Food Court,Fort,18.933198,72.829170,"[{'label': 'display', 'lat': 18.93319755884302...",898,NaN,IN,Mumbai,Mahārāshtra,India,"[Fort, Mumbai, Mahārāshtra, India]",NaN,4e2943f02271752a459cb122
3,Cafeteria at Indian Hotels,None,Oxford Towers,18.922937,72.832849,"[{'label': 'display', 'lat': 18.922937, 'lng':...",1781,NaN,IN,NaN,Mahārāshtra,India,"[Oxford Towers, Mahārāshtra, India]",NaN,4bdfcc5affdec9286e31eda1
4,Cafeteria,None,Mumbai central station,18.970839,72.820636,"[{'label': 'display', 'lat': 18.97083858982881...",3890,NaN,IN,Mumbai,Mahārāshtra,India,"[Mumbai central station, Mumbai, Mahārāshtra, ...",NaN,4d53497cd4a6721ec05589ac

In [130]:
# delete unnecessary columns
clean_Cafeteria_dataframe2= clean_Cafeteria_dataframe.drop(['cc', 'city', 'country', 'crossStreet', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'id'], axis=1)
clean_Cafeteria_dataframe2

,name,categories,address,lat,lng,postalCode,state
0,Cafeteria,Café,Breach Candy Hospital,18.971833,72.804981,400026,Mahārāshtra
1,Cafeteria at Tata Capital,Food Court,One Forbes,18.930769,72.835434,NaN,Mahārāshtra
2,Mumbai High Court Cafeteria,Food Court,Fort,18.933198,72.829170,NaN,Mahārāshtra
3,Cafeteria at Indian Hotels,None,Oxford Towers,18.922937,72.832849,NaN,Mahārāshtra
4,Cafeteria,None,Mumbai central station,18.970839,72.820636,NaN,Mahārāshtra
5,KES College of Commerce & Arts Cafeteria,College Cafeteria,Parekh lane,18.948587,72.829424,400067,Mahārāshtra
6,Cafeteria - P2 Building,Cafeteria,Next to Phoenix Building,18.992866,72.823965,400013,Mahārāshtra
7,"Cafeteria, Lodha Excelus",Cafeteria,"9th Floor, Lodha Excelus,",18.994027,72.834380,400011,Mahārāshtra
8,Burhani College Cafeteria,College Cafeteria,Opp St Mary's School ICSE,18.964665,72.843831,NaN,Mahārāshtra
9,G2W Cafeteria,Cafeteria,NaN,18.974342,72.813182,NaN,NaN
10,Jan Ahaar Cafeteria,Diner,Mumbai Central Station,18.975868,72.823434,NaN,NaN
11,Jai Hind College,College Academic Building,"A Road, Churchgate",18.934689,72.824822,400 020,Mahārāshtra
12,Essar Cafeteria,Food,NaN,18.979570,72.819515,NaN,Mahārāshtra
13,Leo Burnett Cafeteria,Cafeteria,36-A Big Apple,18.998785,72.840376,400012,Mahārāshtra
14,Empire Cafeteria (Siddhi caterers),Café,"Empire Mills Compound, Tulsi Pipe Rd",19.000831,72.828339,NaN,Mahārāshtra
15,Ashok Towers Cafeteria,Café,Ashok Towers,18.997597,72.837888,NaN,Mahārāshtra
16,Adfactors PR Cafeteria,Buffet,NaN,19.005008,72.826450,NaN,NaN
17,Mahindra Towers Cafeteria,Cafeteria,Worli,19.006044,72.820630,400030,Mahārāshtra
18,Mahindra Holidays Cafeteria,Snack Place,"Mahindra Holidays, Mahindra Towers, G.M. Bhosl...",19.005692,72.822309,400018,Mahārāshtra
19,burhani college,College Arts Building,Mazagoan,18.970446,72.835390,400010,Mahārāshtra
20,VIT Executive Cafeteria,College Cafeteria,Vidyalankar Institute Of Technology,19.021675,72.870364,400037,Mahārāshtra
21,welingkar cafeteria,Cafeteria,NaN,19.025060,72.850341,NaN,NaN
22,Price Waterhouse Coopers cafeteria,Café,NaN,19.030498,72.838367,NaN,NaN
23,Leo Burnett India,Office,NaN,18.998824,72.840360,NaN,NaN
24,Bloomberg UTV,Food Court,NaN,18.996877,72.819759,NaN,NaN
25,Indigo Consulting,Building,The Big Apple,18.998891,72.840350,400012,Mahārāshtra
26,BloombergUTV,Food Court,"Parijaat House, 1076, Dr. E Moses Road,",18.996397,72.819472,400018,Mahārāshtra
27,Network 18,Office,"New Empire Complex, Lower Parel (w)",19.031835,72.845926,NaN,Mahārāshtra

In [131]:
# delete rows with none values
df_Cafeteria = clean_Cafeteria_dataframe2.dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
df_Cafeteria

,name,categories,address,lat,lng,postalCode,state
0,Cafeteria,Café,Breach Candy Hospital,18.971833,72.804981,400026,Mahārāshtra
5,KES College of Commerce & Arts Cafeteria,College Cafeteria,Parekh lane,18.948587,72.829424,400067,Mahārāshtra
6,Cafeteria - P2 Building,Cafeteria,Next to Phoenix Building,18.992866,72.823965,400013,Mahārāshtra
7,"Cafeteria, Lodha Excelus",Cafeteria,"9th Floor, Lodha Excelus,",18.994027,72.834380,400011,Mahārāshtra
11,Jai Hind College,College Academic Building,"A Road, Churchgate",18.934689,72.824822,400 020,Mahārāshtra
13,Leo Burnett Cafeteria,Cafeteria,36-A Big Apple,18.998785,72.840376,400012,Mahārāshtra
17,Mahindra Towers Cafeteria,Cafeteria,Worli,19.006044,72.820630,400030,Mahārāshtra
18,Mahindra Holidays Cafeteria,Snack Place,"Mahindra Holidays, Mahindra Towers, G.M. Bhosl...",19.005692,72.822309,400018,Mahārāshtra
19,burhani college,College Arts Building,Mazagoan,18.970446,72.835390,400010,Mahārāshtra
20,VIT Executive Cafeteria,College Cafeteria,Vidyalankar Institute Of Technology,19.021675,72.870364,400037,Mahārāshtra
25,Indigo Consulting,Building,The Big Apple,18.998891,72.840350,400012,Mahārāshtra
26,BloombergUTV,Food Court,"Parijaat House, 1076, Dr. E Moses Road,",18.996397,72.819472,400018,Mahārāshtra

In [ ]:
#Shopping

In [132]:
# search for Shopping
search_query = 'Shopping'
radius = 1000

# Define the corresponding URL
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(ClIENT_ID, ClIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)
url

'https://api.foursquare.com/v2/venues/search?client_id=KL3RTTROV0N33KJKSUK0MKY4D12LIQDWUIOHX10M4OBHVH34&client_secret=P45QAU0PNKG4WX1PVNVTGZUP2ZU1ZRNYAMA33HJKSQZJUBF1&ll=18.9387711,72.8353355&v=20180604&query=Shopping&radius=1000&limit=30'

In [133]:
# Send the GET Request and examine the results
sresults = requests.get(url).json()
#sresults

In [134]:

# assign relevant part of JSON to venues
venues = sresults['response']['venues']

# tranform venues into a dataframe
Shopping_dataframe = json_normalize(venues)
Shopping_dataframe.head()

C:\Users\Acer\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  """

,id,name,categories,referralId,hasPerk,location.lat,location.lng,location.labeledLatLngs,location.distance,location.cc,location.city,location.state,location.country,location.formattedAddress
0,4e54cc34ae60e3d6b7f18c28,Ashoka Shopping Centre,"[{'id': '4bf58dd8d48988d124941735', 'name': 'O...",v-1590405170,False,18.945182,72.832121,"[{'label': 'display', 'lat': 18.94518213019515...",789,IN,Mumbai,Mahārāshtra,India,"[Mumbai, Mahārāshtra, India]"
1,527b9fd8498e3c08ce24052d,Ashrafi Shopping Centre,"[{'id': '4bf58dd8d48988d124941735', 'name': 'O...",v-1590405170,False,18.948688,72.836013,"[{'label': 'display', 'lat': 18.9486880047746,...",1106,IN,NaN,NaN,India,[India]
2,4ecf3a6ce5faa5ec01659919,Bhangwadi Shopping Arcade,"[{'id': '4bf58dd8d48988d124941735', 'name': 'O...",v-1590405170,False,18.946791,72.827999,"[{'label': 'display', 'lat': 18.94679133422852...",1180,IN,NaN,NaN,India,[India]

In [135]:

# keep only columns that include venue name, and anything that is associated with location
Shopping_clean_columns = ['name', 'categories'] + [col for col in Shopping_dataframe.columns if col.startswith('location.')]+ ['id']
clean_Shopping_dataframe = Shopping_dataframe.loc[:,Shopping_clean_columns]

# function that extracts the category of the venue
def get_category_type(row):
    try:
        categories_list5 = row['categories']
    except:
        categories_list5 = row['venue.categories']
        
    if len(categories_list5) == 0:
        return None
    else:
        return categories_list5[0]['name']

# filter the category for each row
clean_Shopping_dataframe['categories'] = clean_Shopping_dataframe.apply(get_category_type, axis=1)

# clean column names by keeping only last term
clean_Shopping_dataframe.columns = [column.split('.')[-1] for column in clean_Shopping_dataframe.columns]

clean_Shopping_dataframe.head()

,name,categories,lat,lng,labeledLatLngs,distance,cc,city,state,country,formattedAddress,id
0,Ashoka Shopping Centre,Office,18.945182,72.832121,"[{'label': 'display', 'lat': 18.94518213019515...",789,IN,Mumbai,Mahārāshtra,India,"[Mumbai, Mahārāshtra, India]",4e54cc34ae60e3d6b7f18c28
1,Ashrafi Shopping Centre,Office,18.948688,72.836013,"[{'label': 'display', 'lat': 18.9486880047746,...",1106,IN,NaN,NaN,India,[India],527b9fd8498e3c08ce24052d
2,Bhangwadi Shopping Arcade,Office,18.946791,72.827999,"[{'label': 'display', 'lat': 18.94679133422852...",1180,IN,NaN,NaN,India,[India],4ecf3a6ce5faa5ec01659919

In [136]:
# delete unnecessary columns
clean_Shopping_dataframe2= clean_Shopping_dataframe.drop(['cc', 'city', 'country', 'distance', 'formattedAddress',\
                                        'labeledLatLngs', 'id'], axis=1)
clean_Shopping_dataframe2

                        name categories        lat        lng        state
0     Ashoka Shopping Centre     Office  18.945182  72.832121  Mahārāshtra
1    Ashrafi Shopping Centre     Office  18.948688  72.836013          NaN
2  Bhangwadi Shopping Arcade     Office  18.946791  72.827999          NaN

In [ ]:
# create dataframe of hotels, shopping stores and Cafeteria

In [137]:

hotel_neighbourhood_df = pd.concat([df_hotel, df_Cafeteria, df_Shopping], ignore_index=True)
hotel_neighbourhood_df

,name,categories,address,lat,lng,postalCode,state
0,Residency Hotel,Hotel,"26, Corner of D.N. Road and Rustom Sidhwa Marg...",18.934978,72.833481,400001,Mahārāshtra
1,Benazeer Hotel,Hotel,16 Gunbow Street,18.935140,72.833948,400001,Mahārāshtra
2,Cafeteria,Café,Breach Candy Hospital,18.971833,72.804981,400026,Mahārāshtra
3,KES College of Commerce & Arts Cafeteria,College Cafeteria,Parekh lane,18.948587,72.829424,400067,Mahārāshtra
4,Cafeteria - P2 Building,Cafeteria,Next to Phoenix Building,18.992866,72.823965,400013,Mahārāshtra
5,"Cafeteria, Lodha Excelus",Cafeteria,"9th Floor, Lodha Excelus,",18.994027,72.834380,400011,Mahārāshtra
6,Jai Hind College,College Academic Building,"A Road, Churchgate",18.934689,72.824822,400 020,Mahārāshtra
7,Leo Burnett Cafeteria,Cafeteria,36-A Big Apple,18.998785,72.840376,400012,Mahārāshtra
8,Mahindra Towers Cafeteria,Cafeteria,Worli,19.006044,72.820630,400030,Mahārāshtra
9,Mahindra Holidays Cafeteria,Snack Place,"Mahindra Holidays, Mahindra Towers, G.M. Bhosl...",19.005692,72.822309,400018,Mahārāshtra
10,burhani college,College Arts Building,Mazagoan,18.970446,72.835390,400010,Mahārāshtra
11,VIT Executive Cafeteria,College Cafeteria,Vidyalankar Institute Of Technology,19.021675,72.870364,400037,Mahārāshtra
12,Indigo Consulting,Building,The Big Apple,18.998891,72.840350,400012,Mahārāshtra
13,BloombergUTV,Food Court,"Parijaat House, 1076, Dr. E Moses Road,",18.996397,72.819472,400018,Mahārāshtra

In [ ]:
# Generate map to visualize hotel neighbourhood including shopping stores and Cafeteria

In [138]:

hotel_map = folium.Map(location=[latitude, longitude], zoom_start=14)

for lat, lng, name, categories, address in zip(hotel_neighbourhood_df['lat'], hotel_neighbourhood_df['lng'], 
                                           hotel_neighbourhood_df['name'], hotel_neighbourhood_df['categories'],\
                                               hotel_neighbourhood_df['address']):
    label = '{}, {}'.format(name, address)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='blue',
        fill_opacity=0.7,
        parse_html=False).add_to(hotel_map)  
    
hotel_map

In [ ]:
 #create dataframe of Park, Restaurant and Cafeteria

In [139]:

park_neighbourhood_df = pd.concat([df_park, df_Restaurant, df_Cafeteria,], ignore_index=True)
park_neighbourhood_df

,name,categories,address,lat,lng,postalCode,state
0,Harish Mahindra Children's Park,Park,"Breach Candy, Behind American Counsulate",18.914867,72.823688,400026,Mahārāshtra
1,Priyadarshini Park,Park,Nepean Sea Road,18.957515,72.799614,400006,Mahārāshtra
2,Nanumal Bhojraj Restaurant - Fort,Indian Restaurant,"Near GPO, Fort, VT",18.937974,72.837663,400001,Mahārāshtra
3,Iran Like Restaurant,Indian Restaurant,"Palton Road, Near Haj House",18.945343,72.836809,400001,Mahārāshtra
4,Stadium Restaurant & Stores,Indian Restaurant,Veer Nariman Road,18.933173,72.826929,400023,Mahārāshtra
5,Nanumal Bhojraj Restaurant - Masjid Bunder,Indian Restaurant,"Gaumukh Bhawan, Masjid Bunder West, Near Masji...",18.953200,72.837577,400009,Mahārāshtra
6,Lalit restaurant,Bar,Cawasji Patel road,18.935002,72.833791,400001,Mahārāshtra
7,Pine Restaurant,Indian Restaurant,"Nawab Tank Bunder, Dockyard",18.964799,72.844015,400010,Mahārāshtra
8,Excellensea Restaurant,BBQ Joint,Mint Road,18.935266,72.837240,400001,Mahārāshtra
9,National Restaurant,Food,opp fort market,18.935112,72.836896,400001,Mahārāshtra
10,Fountain Sizzlers Restaurant,Steakhouse,57 Mahatma Gandhi Road,18.931366,72.831462,400 023,Mahārāshtra
11,Cafeteria,Café,Breach Candy Hospital,18.971833,72.804981,400026,Mahārāshtra
12,KES College of Commerce & Arts Cafeteria,College Cafeteria,Parekh lane,18.948587,72.829424,400067,Mahārāshtra
13,Cafeteria - P2 Building,Cafeteria,Next to Phoenix Building,18.992866,72.823965,400013,Mahārāshtra
14,"Cafeteria, Lodha Excelus",Cafeteria,"9th Floor, Lodha Excelus,",18.994027,72.834380,400011,Mahārāshtra
15,Jai Hind College,College Academic Building,"A Road, Churchgate",18.934689,72.824822,400 020,Mahārāshtra
16,Leo Burnett Cafeteria,Cafeteria,36-A Big Apple,18.998785,72.840376,400012,Mahārāshtra
17,Mahindra Towers Cafeteria,Cafeteria,Worli,19.006044,72.820630,400030,Mahārāshtra
18,Mahindra Holidays Cafeteria,Snack Place,"Mahindra Holidays, Mahindra Towers, G.M. Bhosl...",19.005692,72.822309,400018,Mahārāshtra
19,burhani college,College Arts Building,Mazagoan,18.970446,72.835390,400010,Mahārāshtra
20,VIT Executive Cafeteria,College Cafeteria,Vidyalankar Institute Of Technology,19.021675,72.870364,400037,Mahārāshtra
21,Indigo Consulting,Building,The Big Apple,18.998891,72.840350,400012,Mahārāshtra
22,BloombergUTV,Food Court,"Parijaat House, 1076, Dr. E Moses Road,",18.996397,72.819472,400018,Mahārāshtra

In [140]:

park_map = folium.Map(location=[latitude, longitude], zoom_start=14)

for lat, lng, name, categories, address in zip(park_neighbourhood_df['lat'], park_neighbourhood_df['lng'], 
                                           park_neighbourhood_df['name'], park_neighbourhood_df['categories'],\
                                               park_neighbourhood_df['address']):
    label = '{}, {}'.format(name, address)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='blue',
        fill_opacity=0.7,
        parse_html=False).add_to(park_map)  
    
park_map